name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main
        with:
          spago: "unstable"
      - run: spago build
      - run: spago test
